version: '3'

services:
  file-storage:
    build:
      context: file-storage-microservice
    ports:
      - "8080:8080"

  inventory:
    build:
      context: inventory-microservice
    ports:
      - "8081:8080"

  mobile-bff:
    build:
      context: mobile-bff-microservice
    ports:
      - "8082:8080"

  recommendation:
    build:
      context: recommendation-microservice
    ports:
      - "8083:8080"

  web-bff:
    build:
      context: web-bff-microservice
    ports:
      - "8084:8080"
